[package]
name = "zowex"
version = "0.2.1"
authors = ["Zowe Project"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rpassword = "5.0"
sysinfo = "0.20.0"
