###############################################################################
# Name of the Imperative CLI to generate web help for.
# Set it to `null` to generate help for the CLI in this repo.
# To generate help for another CLI, install it as an NPM package in the
# "web-help" folder and provide its name here (e.g., "@brightside/core"). In
# order for the script to find the NPM package, it must be located in a
# "node_modules" subfolder. You can install it to this folder with the
# command `mkdir node_modules && npm install <cliPackage> --no-package-lock`,
# or point to an existing install with a symlink.
###############################################################################
cliPackage: null

###############################################################################
# List of command groups to exclude from generated docs.
# For example, if you have the CICS plugin globally installed but don't want
# it included in the docs, add "cics" to this list.
###############################################################################
excludeGroups:
  -
