###############################################################################
# Name of the Imperative CLI to generate web help for.
# Set it to `null` to generate help for the CLI in this repo.
# To generate help for another CLI, specify its name here
# (e.g., "@brightside/core") and install its NPM package in the "web-help"
# folder. Ensure the folder "web-help/node_modules" exists before installing
# the package, to prevent NPM from installing to the root folder of the repo.
# To install the CLI package, run this command in the "web-help" folder:
#   npm install <cliPackage> --no-package-lock
# Alternatively, run this command to link to a globally installed package:
#   npm link <cliPackage>
###############################################################################
cliPackage: null

###############################################################################
# List of command groups to exclude from generated docs.
# For example, if you have the CICS plugin globally installed but don't want
# it included in the docs, add "cics" to this list.
###############################################################################
excludeGroups:
  -
