---
# answer how to allow env vars
# config.js for pro users
- default:
    services:
        - zosmf:
            - tso1:
                host: some.host.com
                port: 443
            - ca11:
                port: 443
                rejectUnauthorized: false
                host: usilca11.lvn.broadcom.net