---
# answer how to allow env vars
# config.js for pro users
- default:
    host: "some.host.com"
    port: 443
    services:
        - zosmf:
            - ca11:
                host: some.host.com
                port: 333
                rejectUnauthorized: true
        