name: Rust CLI CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose --manifest-path=zowe2/Cargo.toml
    - name: Run tests
      run: cargo test --verbose --manifest-path=zowe2/Cargo.toml