name: Rust CLI CI

on: [push, pull_request]

jobs:
  build_and_test:
    name: Rust CLI Zowe Client
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features
          working-directory: zowe2
      - uses: marcopolo/cargo@master
        with:
          command: test
          working-directory: zowe2
